export type SadhanaCategory =
  | 'all'
  | 'shakti'
  | 'shiva'
  | 'vishnu'
  | 'ganapati'
  | 'hanuman'
  | 'vedic'
  | 'tantric'
  | 'protection';

export interface SadhanaSource {
  textEn: string;
  textHi: string;
  reference?: string;
}

export interface Sadhana {
  id: string;
  category: SadhanaCategory;
  nameEn: string;
  nameHi: string;
  deityEn: string;
  deityHi: string;
  purposeEn: string;
  purposeHi: string;

  bestTithiEn: string;
  bestTithiHi: string;
  bestVaarEn: string;
  bestVaarHi: string;
  bestTimeEn: string;
  bestTimeHi: string;
  bestNakshatraEn?: string;
  bestNakshatraHi?: string;

  durationEn: string;
  durationHi: string;
  mantra: string;
  mantraTransliteration: string;
  japaCount: number;

  methodEn: string[];
  methodHi: string[];

  precautionsEn: string[];
  precautionsHi: string[];

  sources: SadhanaSource[];
}

export const SADHANA_CATEGORIES: { code: SadhanaCategory; en: string; hi: string; emoji: string }[] = [
  { code: 'all', en: 'All', hi: 'सभी', emoji: '🕉️' },
  { code: 'shakti', en: 'Shakti / Devi', hi: 'शक्ति / देवी', emoji: '🌺' },
  { code: 'shiva', en: 'Shiva', hi: 'शिव', emoji: '🔱' },
  { code: 'vishnu', en: 'Vishnu / Krishna', hi: 'विष्णु / कृष्ण', emoji: '🪷' },
  { code: 'ganapati', en: 'Ganapati', hi: 'गणपति', emoji: '🐘' },
  { code: 'hanuman', en: 'Hanuman', hi: 'हनुमान', emoji: '🙏' },
  { code: 'vedic', en: 'Vedic', hi: 'वैदिक', emoji: '📜' },
  { code: 'tantric', en: 'Tantric', hi: 'तांत्रिक', emoji: '🔯' },
  { code: 'protection', en: 'Kavach / Protection', hi: 'कवच / रक्षा', emoji: '🛡️' },
];

export const SADHANAS: Sadhana[] = [
  {
    id: 'ganapati-atharvashirsha',
    category: 'ganapati',
    nameEn: 'Ganapati Atharvashirsha Sadhana',
    nameHi: 'गणपति अथर्वशीर्ष साधना',
    deityEn: 'Lord Ganapati',
    deityHi: 'भगवान गणपति',
    purposeEn: 'Removal of obstacles, success in new ventures, wisdom and intelligence',
    purposeHi: 'विघ्नों का नाश, नए कार्यों में सफलता, बुद्धि और विवेक की प्राप्ति',
    bestTithiEn: 'Chaturthi (4th tithi) of Shukla Paksha (waxing moon)',
    bestTithiHi: 'शुक्ल पक्ष की चतुर्थी तिथि',
    bestVaarEn: 'Tuesday or Wednesday',
    bestVaarHi: 'मंगलवार या बुधवार',
    bestTimeEn: 'Brahma Muhurat (4:00–6:00 AM) or Madhyahna (mid-day)',
    bestTimeHi: 'ब्रह्म मुहूर्त (प्रातः 4:00–6:00) या मध्याह्न',
    bestNakshatraEn: 'Hasta, Chitra, Swati',
    bestNakshatraHi: 'हस्त, चित्रा, स्वाति',
    durationEn: '21 or 41 days continuous',
    durationHi: '21 या 41 दिन निरंतर',
    mantra: 'ॐ गं गणपतये नमः',
    mantraTransliteration: 'Om Gam Ganapataye Namah',
    japaCount: 108,
    methodEn: [
      'Bathe, wear clean red or yellow clothes, face East',
      'Place a Ganesha murti or yantra on a red cloth',
      'Offer durva grass (21 blades), red flowers, modak/laddu',
      'Light a ghee lamp and dhoop',
      'Recite the Atharvashirsha 1, 11, or 21 times daily',
      'Conclude with japa of root mantra on rudraksha mala',
    ],
    methodHi: [
      'स्नान करके लाल या पीले स्वच्छ वस्त्र धारण करें, पूर्व मुख होकर बैठें',
      'लाल वस्त्र पर गणेश मूर्ति या यंत्र स्थापित करें',
      'दूर्वा (21), लाल पुष्प, मोदक/लड्डू अर्पित करें',
      'घी का दीपक और धूप जलाएं',
      'प्रतिदिन अथर्वशीर्ष का 1, 11 या 21 बार पाठ करें',
      'रुद्राक्ष माला से मूल मंत्र का जप करें',
    ],
    precautionsEn: [
      'Do not break the daily routine—if missed, start over',
      'Maintain brahmacharya (celibacy) and satvik food during sadhana',
      'Avoid anger, harsh speech, and alcohol',
    ],
    precautionsHi: [
      'दैनिक नियम न तोड़ें—यदि छूट जाए तो पुनः आरम्भ करें',
      'साधना काल में ब्रह्मचर्य और सात्विक आहार रखें',
      'क्रोध, कटु वचन और मद्यपान से बचें',
    ],
    sources: [
      { textEn: 'Ganapati Atharvashirsha Upanishad', textHi: 'गणपति अथर्वशीर्ष उपनिषद्', reference: 'Atharvaveda' },
      { textEn: 'Mantra Mahodadhi', textHi: 'मंत्र महोदधि', reference: 'Taranga 1' },
    ],
  },
  {
    id: 'mahamrityunjaya',
    category: 'shiva',
    nameEn: 'Mahamrityunjaya Sadhana',
    nameHi: 'महामृत्युंजय साधना',
    deityEn: 'Lord Shiva (Mrityunjaya)',
    deityHi: 'भगवान शिव (मृत्युंजय)',
    purposeEn: 'Victory over untimely death, healing of disease, longevity, removal of fear',
    purposeHi: 'अकाल मृत्यु पर विजय, रोग नाश, दीर्घायु, भय का नाश',
    bestTithiEn: 'Trayodashi (13th), Chaturdashi (14th) and Pradosh, especially of Krishna Paksha',
    bestTithiHi: 'त्रयोदशी, चतुर्दशी एवं प्रदोष—विशेषतः कृष्ण पक्ष',
    bestVaarEn: 'Monday',
    bestVaarHi: 'सोमवार',
    bestTimeEn: 'Brahma Muhurat or Pradosh Kaal (sunset)',
    bestTimeHi: 'ब्रह्म मुहूर्त या प्रदोष काल (सूर्यास्त)',
    bestNakshatraEn: 'Ardra, Pushya, Shravana',
    bestNakshatraHi: 'आर्द्रा, पुष्य, श्रवण',
    durationEn: '40 days; full anushthan = 125,000 japa',
    durationHi: '40 दिन; पूर्ण अनुष्ठान = 1,25,000 जप',
    mantra: 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्।\nउर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात्॥',
    mantraTransliteration: 'Om Tryambakam Yajamahe Sugandhim Pushti-vardhanam | Urvarukamiva Bandhanan Mrityor Mukshiya Mamritat',
    japaCount: 108,
    methodEn: [
      'Bathe and wear white or rudraksha-coloured clothes, face North or East',
      'Place a Shivalinga; offer bilva patra, white flowers, ganga jala',
      'Abhishek with milk + water + honey during japa',
      'Use rudraksha mala (108 beads), keep mala covered',
      'Optional: dhuni with samidha of palash + ghee + sesame for hawan',
      'After japa, do Rudrabhishek every Monday',
    ],
    methodHi: [
      'स्नान कर श्वेत वस्त्र धारण करें, उत्तर या पूर्व मुख बैठें',
      'शिवलिंग की स्थापना करें; बेलपत्र, श्वेत पुष्प, गंगाजल अर्पित करें',
      'जप के साथ दूध+जल+शहद से अभिषेक करें',
      '108 दानों की रुद्राक्ष माला का प्रयोग करें, माला ढककर रखें',
      'पलाश समिधा + घी + तिल से हवन (वैकल्पिक)',
      'अनुष्ठान के बाद प्रत्येक सोमवार रुद्राभिषेक करें',
    ],
    precautionsEn: [
      'Never use this mantra for harming others—it is a healing mantra',
      'Strict satvik diet—no onion, garlic, tamasic food during sadhana',
      'Do not interrupt the daily count; if broken, restart',
    ],
    precautionsHi: [
      'इस मंत्र का प्रयोग कभी किसी को हानि पहुँचाने के लिए न करें—यह रोग-नाशक मंत्र है',
      'साधना काल में पूर्ण सात्विक आहार—प्याज, लहसुन, तामसिक पदार्थ वर्जित',
      'दैनिक संख्या न टूटे; टूटने पर अनुष्ठान पुनः आरम्भ करें',
    ],
    sources: [
      { textEn: 'Rigveda 7.59.12 (Rishi Vasishtha)', textHi: 'ऋग्वेद 7.59.12 (ऋषि वसिष्ठ)' },
      { textEn: 'Yajurveda (Rudradhyaya)', textHi: 'यजुर्वेद (रुद्राध्याय)' },
      { textEn: 'Mantra Mahodadhi by Mahidhara', textHi: 'मंत्र महोदधि (महीधर)', reference: 'Taranga 22' },
    ],
  },
  {
    id: 'navarna-durga',
    category: 'shakti',
    nameEn: 'Navarna Mantra (Durga) Sadhana',
    nameHi: 'नवार्ण मंत्र (दुर्गा) साधना',
    deityEn: 'Maa Durga / Chandika',
    deityHi: 'माँ दुर्गा / चण्डिका',
    purposeEn: 'Removal of enemies & negativity, victory in struggle, blessings of Shakti',
    purposeHi: 'शत्रु एवं नकारात्मकता का नाश, संघर्ष में विजय, शक्ति की कृपा',
    bestTithiEn: 'Ashtami, Navami, and the 9 nights of Navratri (Chaitra & Sharad)',
    bestTithiHi: 'अष्टमी, नवमी एवं नवरात्रि की 9 रात्रियाँ (चैत्र व शारदीय)',
    bestVaarEn: 'Tuesday, Friday, Saturday',
    bestVaarHi: 'मंगलवार, शुक्रवार, शनिवार',
    bestTimeEn: 'Nishita Kaal (midnight) or Brahma Muhurat',
    bestTimeHi: 'निशीथ काल (मध्य रात्रि) या ब्रह्म मुहूर्त',
    bestNakshatraEn: 'Mool, Chitra, Magha',
    bestNakshatraHi: 'मूल, चित्रा, मघा',
    durationEn: 'Navratri (9 days) or full anushthan = 125,000 japa',
    durationHi: 'नवरात्रि (9 दिन) या पूर्ण अनुष्ठान = 1,25,000 जप',
    mantra: 'ॐ ऐं ह्रीं क्लीं चामुण्डायै विच्चे',
    mantraTransliteration: 'Om Aim Hrim Klim Chamundayai Vichche',
    japaCount: 108,
    methodEn: [
      'Establish Kalash and Durga yantra on red cloth',
      'Light akhand jyoti (continuous lamp) for full Navratri',
      'Offer red flowers (hibiscus), red chunni, kumkum, akshat',
      'Do path of Durga Saptashati daily (full or selected chapters)',
      'Japa with red coral or rudraksha mala, face East or North',
      'Conclude with hawan, kanya pujan and brahman bhojan',
    ],
    methodHi: [
      'लाल वस्त्र पर कलश व दुर्गा यंत्र स्थापित करें',
      'पूरे नवरात्रि अखंड ज्योति प्रज्ज्वलित रखें',
      'लाल पुष्प (गुड़हल), लाल चुनरी, कुमकुम, अक्षत अर्पित करें',
      'प्रतिदिन दुर्गा सप्तशती का पाठ करें (पूर्ण या चयनित अध्याय)',
      'मूँगा या रुद्राक्ष माला से जप, पूर्व या उत्तर मुख',
      'समापन हवन, कन्या पूजन और ब्राह्मण भोजन से करें',
    ],
    precautionsEn: [
      'Strict celibacy and satvik food throughout',
      'No haircut, nail cutting, or shaving during sadhana',
      'Saptashati path should be done with proper sankalpa, kavach, argala, keelak',
    ],
    precautionsHi: [
      'सम्पूर्ण काल में ब्रह्मचर्य व सात्विक भोजन',
      'साधना के दौरान बाल, नाखून, क्षौर (शेविंग) वर्जित',
      'सप्तशती पाठ संकल्प, कवच, अर्गला, कीलक सहित करें',
    ],
    sources: [
      { textEn: 'Markandeya Purana — Durga Saptashati', textHi: 'मार्कण्डेय पुराण — दुर्गा सप्तशती' },
      { textEn: 'Devi Atharvashirsha', textHi: 'देवी अथर्वशीर्ष', reference: 'Atharvaveda' },
      { textEn: 'Mantra Mahodadhi', textHi: 'मंत्र महोदधि', reference: 'Taranga 4' },
    ],
  },
  {
    id: 'bagalamukhi',
    category: 'tantric',
    nameEn: 'Bagalamukhi Sadhana',
    nameHi: 'बगलामुखी साधना',
    deityEn: 'Maa Bagalamukhi (Pitambara Vidya)',
    deityHi: 'माँ बगलामुखी (पीताम्बरा विद्या)',
    purposeEn: 'Stambhan (paralysis) of enemies, victory in litigation, debate and conflict',
    purposeHi: 'शत्रुओं का स्तम्भन, मुकदमे/वाद-विवाद/संघर्ष में विजय',
    bestTithiEn: 'Chaturdashi of Krishna Paksha, especially when falling on Tuesday',
    bestTithiHi: 'कृष्ण पक्ष की चतुर्दशी, विशेषतः मंगलवार को पड़ने पर',
    bestVaarEn: 'Tuesday (Bhauma)',
    bestVaarHi: 'मंगलवार',
    bestTimeEn: 'Nishita Kaal (midnight) — Veer Kaal',
    bestTimeHi: 'निशीथ काल (मध्य रात्रि) — वीर काल',
    bestNakshatraEn: 'Mool, Pushya',
    bestNakshatraHi: 'मूल, पुष्य',
    durationEn: '11, 21, or 40 days; purna anushthan = 125,000 japa',
    durationHi: '11, 21 या 40 दिन; पूर्ण अनुष्ठान = 1,25,000 जप',
    mantra: 'ॐ ह्लीं बगलामुखि सर्वदुष्टानां वाचं मुखं पदं स्तम्भय जिह्वां कीलय बुद्धिं विनाशय ह्लीं ॐ स्वाहा',
    mantraTransliteration: 'Om Hlrim Bagalamukhi Sarva-dushtanam Vacham Mukham Padam Stambhaya Jihvam Kilaya Buddhim Vinashaya Hlrim Om Svaha',
    japaCount: 108,
    methodEn: [
      'Wear yellow clothes, sit on yellow asan, face East',
      'Establish Bagalamukhi yantra on yellow cloth',
      'Offer yellow flowers, turmeric, yellow naivedya (besan laddu, kesar)',
      'Use turmeric (haldi) mala for japa',
      'Mandatory: take diksha from a qualified Guru before starting this sadhana',
    ],
    methodHi: [
      'पीले वस्त्र पहनें, पीले आसन पर पूर्व मुख बैठें',
      'पीले वस्त्र पर बगलामुखी यंत्र स्थापित करें',
      'पीले पुष्प, हल्दी, पीला नैवेद्य (बेसन लड्डू, केसर) अर्पित करें',
      'जप हेतु हल्दी (हरिद्रा) माला का प्रयोग करें',
      'अनिवार्य: साधना से पूर्व योग्य गुरु से दीक्षा अवश्य लें',
    ],
    precautionsEn: [
      '⚠️ Do NOT perform without proper guru-diksha—this is an Ugra (fierce) Vidya',
      'Never use for personal revenge or harming innocents',
      'Strict celibacy, silence (mauna) during japa hours',
      'Sadhana room should be locked and private',
    ],
    precautionsHi: [
      '⚠️ बिना गुरु-दीक्षा के यह साधना न करें—यह उग्र विद्या है',
      'व्यक्तिगत प्रतिशोध या निर्दोषों को हानि के लिए कभी प्रयोग न करें',
      'जप काल में पूर्ण ब्रह्मचर्य व मौन',
      'साधना कक्ष एकांत व बंद हो',
    ],
    sources: [
      { textEn: 'Mantra Mahodadhi', textHi: 'मंत्र महोदधि', reference: 'Taranga 8 (Mahidhara, 1588 CE)' },
      { textEn: 'Shaktisangama Tantra', textHi: 'शक्तिसंगम तंत्र' },
      { textEn: 'Rudrayamala Tantra', textHi: 'रुद्रयामल तंत्र' },
    ],
  },
  {
    id: 'yogini-sadhana',
    category: 'tantric',
    nameEn: 'Yogini Sadhana (64 Yoginis)',
    nameHi: 'योगिनी साधना (चौंसठ योगिनी)',
    deityEn: '64 Yoginis (associates of Maa Kali / Durga)',
    deityHi: '64 योगिनियाँ (माँ काली / दुर्गा की सहचरी)',
    purposeEn: 'Awakening of siddhis, control over subtle forces, protection from negative energies',
    purposeHi: 'सिद्धियों का जागरण, सूक्ष्म शक्तियों पर नियंत्रण, नकारात्मक ऊर्जा से रक्षा',
    bestTithiEn: 'Ashtami and Chaturdashi of Krishna Paksha; Amavasya',
    bestTithiHi: 'कृष्ण पक्ष की अष्टमी एवं चतुर्दशी; अमावस्या',
    bestVaarEn: 'Tuesday, Saturday',
    bestVaarHi: 'मंगलवार, शनिवार',
    bestTimeEn: 'Nishita Kaal (11:48 PM – 12:36 AM)',
    bestTimeHi: 'निशीथ काल (रात्रि 11:48 – प्रातः 12:36)',
    bestNakshatraEn: 'Mool, Ashlesha, Jyeshtha',
    bestNakshatraHi: 'मूल, आश्लेषा, ज्येष्ठा',
    durationEn: 'Full anushthan = 64 nights (one yogini per night)',
    durationHi: 'पूर्ण अनुष्ठान = 64 रात्रि (एक रात्रि = एक योगिनी)',
    mantra: 'ॐ ऐं ह्रीं श्रीं चतुःषष्ठि योगिनीभ्यो नमः',
    mantraTransliteration: 'Om Aim Hrim Shrim Chatuh-shashthi Yoginibhyo Namah',
    japaCount: 108,
    methodEn: [
      '⚠️ ABSOLUTELY requires diksha from a Tantric guru of a living parampara',
      'Yogini chakra (64-petalled yantra) installed on a copper plate',
      'Offer red flowers, kumkum, saffron, ksheer (milk pudding)',
      'Each yogini has her own bija mantra—Guru imparts the full kramа',
      'Begin only after completing preliminary Devi sadhanas (Durga, Kali)',
    ],
    methodHi: [
      '⚠️ जीवित परम्परा के तांत्रिक गुरु से दीक्षा अनिवार्य',
      'ताम्र पत्र पर 64-दल योगिनी चक्र स्थापित करें',
      'लाल पुष्प, कुमकुम, केसर, खीर अर्पित करें',
      'प्रत्येक योगिनी का अपना बीज मंत्र—गुरु पूर्ण क्रम बताते हैं',
      'पूर्व में दुर्गा/काली साधना पूरी करने के पश्चात ही प्रारम्भ करें',
    ],
    precautionsEn: [
      '⚠️ Extremely advanced sadhana—not for beginners. Improper practice can cause severe harm',
      'Without guru, even uttering the names can backfire',
      'Strict celibacy, satvik food, isolation for the full duration',
      'No mirror, no contact with outsiders during sadhana nights',
    ],
    precautionsHi: [
      '⚠️ अत्यंत उच्च स्तरीय साधना—प्रारंभिक साधकों के लिए नहीं। अनुचित अभ्यास से गंभीर हानि सम्भव',
      'बिना गुरु के नाम उच्चारण भी विपरीत फल दे सकता है',
      'पूर्ण काल में कठोर ब्रह्मचर्य, सात्विक आहार, एकांतवास',
      'साधना रात्रियों में दर्पण, बाह्य व्यक्तियों से सम्पर्क वर्जित',
    ],
    sources: [
      { textEn: 'Yogini Tantra', textHi: 'योगिनी तंत्र' },
      { textEn: 'Rudrayamala Tantra', textHi: 'रुद्रयामल तंत्र' },
      { textEn: 'Kalika Purana', textHi: 'कालिका पुराण' },
      { textEn: 'Brihat Tantrasara by Krishnananda Agamavagisha', textHi: 'बृहत् तंत्रसार (कृष्णानन्द आगमवागीश)' },
    ],
  },
  {
    id: 'mahakali',
    category: 'tantric',
    nameEn: 'Mahakali Sadhana',
    nameHi: 'महाकाली साधना',
    deityEn: 'Maa Mahakali',
    deityHi: 'माँ महाकाली',
    purposeEn: 'Destruction of inner darkness, protection from black magic, fearlessness',
    purposeHi: 'आन्तरिक अंधकार का नाश, अभिचार/तंत्र-बाधा से रक्षा, निर्भयता',
    bestTithiEn: 'Amavasya, Krishna Chaturdashi (especially Kali Chaudas / Narak Chaturdashi)',
    bestTithiHi: 'अमावस्या, कृष्ण चतुर्दशी (विशेषतः काली चौदस / नरक चतुर्दशी)',
    bestVaarEn: 'Tuesday, Saturday',
    bestVaarHi: 'मंगलवार, शनिवार',
    bestTimeEn: 'Nishita Kaal (midnight)',
    bestTimeHi: 'निशीथ काल (मध्य रात्रि)',
    bestNakshatraEn: 'Ashlesha, Mool, Magha',
    bestNakshatraHi: 'आश्लेषा, मूल, मघा',
    durationEn: '21 nights or purna anushthan',
    durationHi: '21 रात्रि या पूर्ण अनुष्ठान',
    mantra: 'क्रीं क्रीं क्रीं ह्रीं ह्रीं ह्रूं ह्रूं दक्षिणे कालिके क्रीं क्रीं क्रीं ह्रीं ह्रीं ह्रूं ह्रूं स्वाहा',
    mantraTransliteration: 'Krim Krim Krim Hrim Hrim Hrum Hrum Dakshine Kalike Krim Krim Krim Hrim Hrim Hrum Hrum Svaha',
    japaCount: 108,
    methodEn: [
      'Black or dark blue cloth seat, face South',
      'Kali yantra of copper or silver',
      'Offer red hibiscus, red sandalwood, ksheer, urad dal',
      'Use rudraksha or human-bone mala (advanced — Guru only)',
      'Light a mustard oil or ghee lamp; do not let it extinguish',
    ],
    methodHi: [
      'काले या गहरे नीले वस्त्र के आसन पर दक्षिण मुख बैठें',
      'ताम्र या रजत का काली यंत्र',
      'लाल गुड़हल, रक्त चंदन, खीर, उड़द दाल अर्पित करें',
      'रुद्राक्ष माला (अनुभवी—गुरु के निर्देशानुसार ही अन्य माला)',
      'सरसों तेल या घी का दीपक प्रज्ज्वलित रखें; बुझने न दें',
    ],
    precautionsEn: [
      '⚠️ Requires guru-diksha; cremation-ground sadhana (shmashan) only under direct supervision',
      'Strict satvik food; no meat/alcohol contrary to popular myth',
      'Not to be done during illness, grief, or mental imbalance',
    ],
    precautionsHi: [
      '⚠️ गुरु-दीक्षा अनिवार्य; श्मशान साधना केवल गुरु के प्रत्यक्ष संरक्षण में',
      'पूर्ण सात्विक भोजन; प्रचलित भ्रम के विपरीत मांस/मद्य वर्जित',
      'रोग, शोक या मानसिक अस्थिरता की अवस्था में न करें',
    ],
    sources: [
      { textEn: 'Mahanirvana Tantra', textHi: 'महानिर्वाण तंत्र' },
      { textEn: 'Kali Tantra', textHi: 'काली तंत्र' },
      { textEn: 'Tantrasara by Krishnananda', textHi: 'तंत्रसार (कृष्णानन्द)' },
      { textEn: 'Karpuradi Stotra (commentary by Sir John Woodroffe)', textHi: 'कर्पूरादि स्तोत्र' },
    ],
  },
  {
    id: 'tripura-sundari',
    category: 'shakti',
    nameEn: 'Shri Vidya (Tripura Sundari) Sadhana',
    nameHi: 'श्री विद्या (त्रिपुर सुन्दरी) साधना',
    deityEn: 'Maa Lalita Tripura Sundari',
    deityHi: 'माँ ललिता त्रिपुर सुन्दरी',
    purposeEn: 'Highest moksha-giving vidya, beauty, prosperity, self-realisation',
    purposeHi: 'सर्वोच्च मोक्षदायिनी विद्या, सौंदर्य, समृद्धि, आत्म-साक्षात्कार',
    bestTithiEn: 'Purnima (full moon), Shukla Panchami, Friday-Ashtami',
    bestTithiHi: 'पूर्णिमा, शुक्ल पंचमी, शुक्र-अष्टमी',
    bestVaarEn: 'Friday',
    bestVaarHi: 'शुक्रवार',
    bestTimeEn: 'Brahma Muhurat or evening Sandhya',
    bestTimeHi: 'ब्रह्म मुहूर्त या सायं सन्ध्या',
    bestNakshatraEn: 'Uttara-phalguni, Hasta, Chitra, Revati',
    bestNakshatraHi: 'उत्तरा-फाल्गुनी, हस्त, चित्रा, रेवती',
    durationEn: 'Lifetime sadhana with Shodashi diksha; minimum 9 months',
    durationHi: 'षोडशी दीक्षा सहित जीवन-पर्यन्त साधना; न्यूनतम 9 मास',
    mantra: 'ॐ ऐं ह्रीं श्रीं श्रीमात्रे नमः  (Panchadashi for diksha-holders)',
    mantraTransliteration: 'Om Aim Hrim Shrim Shri-matre Namah',
    japaCount: 108,
    methodEn: [
      'Shri Yantra on copper, silver, or sphatik (crystal)',
      'Offer red flowers, kumkum, raw milk, white sandalwood',
      'Daily Lalita Sahasranama path (1000 names)',
      'Panchadashi mantra requires diksha; Shodashi only after years of sadhana',
    ],
    methodHi: [
      'ताम्र, रजत या स्फटिक का श्री यंत्र',
      'लाल पुष्प, कुमकुम, कच्चा दूध, श्वेत चंदन अर्पित करें',
      'प्रतिदिन ललिता सहस्रनाम पाठ',
      'पंचदशी मंत्र दीक्षा-अपेक्षित; षोडशी वर्षों की साधना के बाद',
    ],
    precautionsEn: [
      'Shri Vidya is the most sacred and complex tantra—do not self-initiate',
      'Find a Shri Vidya parampara guru (Dakshinamurti, Hayagreeva, or Sankaracharya lineage)',
      'Strict adherence to dharma, satya, ahimsa',
    ],
    precautionsHi: [
      'श्री विद्या सर्वाधिक पवित्र व जटिल तंत्र है—स्व-दीक्षा न करें',
      'श्री विद्या परम्परा के गुरु खोजें (दक्षिणामूर्ति, हयग्रीव या शंकराचार्य परम्परा)',
      'धर्म, सत्य, अहिंसा का कठोर पालन',
    ],
    sources: [
      { textEn: 'Lalita Sahasranama (Brahmanda Purana)', textHi: 'ललिता सहस्रनाम (ब्रह्माण्ड पुराण)' },
      { textEn: 'Parashurama Kalpasutra', textHi: 'परशुराम कल्पसूत्र' },
      { textEn: 'Saundarya Lahari by Adi Shankaracharya', textHi: 'सौन्दर्य लहरी (आदि शंकराचार्य)' },
      { textEn: 'Mantra Mahodadhi', textHi: 'मंत्र महोदधि', reference: 'Taranga 7' },
    ],
  },
  {
    id: 'hanuman',
    category: 'hanuman',
    nameEn: 'Hanuman Sadhana',
    nameHi: 'हनुमान साधना',
    deityEn: 'Shri Hanuman ji',
    deityHi: 'श्री हनुमान जी',
    purposeEn: 'Courage, strength, removal of fear, protection from negative energies & Saturn',
    purposeHi: 'साहस, बल, भय का नाश, बुरी शक्तियों एवं शनि से रक्षा',
    bestTithiEn: 'Chaitra Purnima (Hanuman Jayanti), every Mangalwar & Shanivar',
    bestTithiHi: 'चैत्र पूर्णिमा (हनुमान जयन्ती), प्रत्येक मंगलवार व शनिवार',
    bestVaarEn: 'Tuesday, Saturday',
    bestVaarHi: 'मंगलवार, शनिवार',
    bestTimeEn: 'Sunrise (Suryodaya) or Pradosh',
    bestTimeHi: 'सूर्योदय या प्रदोष काल',
    bestNakshatraEn: 'Chitra, Swati, Anuradha',
    bestNakshatraHi: 'चित्रा, स्वाति, अनुराधा',
    durationEn: '41 days continuous (Mangal anushthan)',
    durationHi: '41 दिन निरंतर (मंगल अनुष्ठान)',
    mantra: 'ॐ हं हनुमते रुद्रात्मकाय हुं फट्',
    mantraTransliteration: 'Om Ham Hanumate Rudratmakaya Hum Phat',
    japaCount: 108,
    methodEn: [
      'Bathe and wear red or orange clothes',
      'Offer sindoor + chameli oil to Hanuman murti',
      'Offer boondi laddu, gud-chana, banana',
      'Recite Hanuman Chalisa 11 times, then Sundarkand on Saturdays',
      'Use red moonga or rudraksha mala for japa',
    ],
    methodHi: [
      'स्नान कर लाल या नारंगी वस्त्र धारण करें',
      'हनुमान मूर्ति पर सिन्दूर + चमेली का तेल अर्पित करें',
      'बूँदी लड्डू, गुड़-चना, केला अर्पित करें',
      'हनुमान चालीसा का 11 बार पाठ, शनिवार को सुन्दरकाण्ड',
      'जप हेतु लाल मूँगा या रुद्राक्ष माला',
    ],
    precautionsEn: [
      'Strict celibacy during the 41-day anushthan',
      'No alcohol, meat, or contact with women (for male sadhakas)',
      'Visit Hanuman temple every Tuesday and Saturday',
    ],
    precautionsHi: [
      '41 दिनों के अनुष्ठान में पूर्ण ब्रह्मचर्य',
      'मद्य, मांस वर्जित; पुरुष साधकों के लिए स्त्री-सम्पर्क वर्जित',
      'प्रत्येक मंगल व शनि को हनुमान मन्दिर अवश्य जाएँ',
    ],
    sources: [
      { textEn: 'Sundarakand — Valmiki Ramayana', textHi: 'सुन्दरकाण्ड — वाल्मीकि रामायण' },
      { textEn: 'Hanuman Chalisa by Tulsidas', textHi: 'हनुमान चालीसा (तुलसीदास)' },
      { textEn: 'Rudrayamala Tantra — Hanuman Khand', textHi: 'रुद्रयामल तंत्र — हनुमान खण्ड' },
      { textEn: 'Sankat Mochan Hanumanashtak', textHi: 'संकट मोचन हनुमानाष्टक' },
    ],
  },
  {
    id: 'sudarshan-kavach',
    category: 'protection',
    nameEn: 'Sudarshan Kavach Sadhana',
    nameHi: 'सुदर्शन कवच साधना',
    deityEn: 'Bhagwan Vishnu — Sudarshan Chakra',
    deityHi: 'भगवान विष्णु — सुदर्शन चक्र',
    purposeEn: 'Total protection from black magic, evil eye, hostile planetary effects',
    purposeHi: 'अभिचार, दृष्टि-दोष, ग्रहों की पीड़ा से पूर्ण रक्षा',
    bestTithiEn: 'Ekadashi, Dwadashi; Vaikuntha Ekadashi is supreme',
    bestTithiHi: 'एकादशी, द्वादशी; वैकुण्ठ एकादशी सर्वश्रेष्ठ',
    bestVaarEn: 'Thursday, Saturday',
    bestVaarHi: 'गुरुवार, शनिवार',
    bestTimeEn: 'Brahma Muhurat',
    bestTimeHi: 'ब्रह्म मुहूर्त',
    bestNakshatraEn: 'Shravana, Rohini',
    bestNakshatraHi: 'श्रवण, रोहिणी',
    durationEn: '21 or 48 days',
    durationHi: '21 या 48 दिन',
    mantra: 'ॐ सहस्रार हुं फट्',
    mantraTransliteration: 'Om Sahasrara Hum Phat',
    japaCount: 108,
    methodEn: [
      'Sudarshan yantra on copper, face East',
      'Offer tulsi patra, yellow flowers, ghee diya',
      'Recite Sudarshan Kavach (from Pancharatra Agama) daily',
      'On completion, do havan with 1008 ahuti of til + ghee + sugar',
    ],
    methodHi: [
      'पूर्व मुख होकर ताम्र पट्ट पर सुदर्शन यंत्र',
      'तुलसी पत्र, पीले पुष्प, घी का दीप अर्पित करें',
      'प्रतिदिन सुदर्शन कवच (पाञ्चरात्र आगम) का पाठ',
      'समापन पर तिल + घी + शक्कर से 1008 आहुति का हवन',
    ],
    precautionsEn: [
      'Only use for self-protection, never to harm others',
      'Maintain vegetarian diet; avoid onion-garlic on Ekadashi',
    ],
    precautionsHi: [
      'केवल आत्म-रक्षा हेतु; अन्य को हानि के लिए कभी प्रयोग न करें',
      'शाकाहारी आहार; एकादशी को प्याज-लहसुन वर्जित',
    ],
    sources: [
      { textEn: 'Atharvaveda — Sudarshan Sukta', textHi: 'अथर्ववेद — सुदर्शन सूक्त' },
      { textEn: 'Ahirbudhnya Samhita (Pancharatra)', textHi: 'अहिर्बुध्न्य संहिता (पाञ्चरात्र)' },
      { textEn: 'Narada Pancharatra', textHi: 'नारद पाञ्चरात्र' },
    ],
  },
  {
    id: 'lakshmi-kubera',
    category: 'shakti',
    nameEn: 'Mahalakshmi–Kubera Sadhana',
    nameHi: 'महालक्ष्मी–कुबेर साधना',
    deityEn: 'Maa Mahalakshmi and Kubera',
    deityHi: 'माँ महालक्ष्मी एवं कुबेर',
    purposeEn: 'Wealth, prosperity, debt removal, abundance',
    purposeHi: 'धन, समृद्धि, ऋण मुक्ति, ऐश्वर्य',
    bestTithiEn: 'Shukla Panchami, Purnima; Diwali Amavasya is supreme',
    bestTithiHi: 'शुक्ल पंचमी, पूर्णिमा; दीवाली अमावस्या सर्वश्रेष्ठ',
    bestVaarEn: 'Friday, Thursday',
    bestVaarHi: 'शुक्रवार, गुरुवार',
    bestTimeEn: 'Pradosh kaal (sunset) or Nishita kaal on Diwali',
    bestTimeHi: 'प्रदोष काल (सूर्यास्त) या दीवाली पर निशीथ काल',
    bestNakshatraEn: 'Rohini, Pushya, Shravana',
    bestNakshatraHi: 'रोहिणी, पुष्य, श्रवण',
    durationEn: '16 Fridays (Shodash Shukrawar) or 11 days',
    durationHi: '16 शुक्रवार (षोडश शुक्रवार) या 11 दिन',
    mantra: 'ॐ श्रीं ह्रीं श्रीं कमले कमलालये प्रसीद प्रसीद श्रीं ह्रीं श्रीं ॐ महालक्ष्म्यै नमः',
    mantraTransliteration: 'Om Shrim Hrim Shrim Kamale Kamalalaye Praseed Praseed Shrim Hrim Shrim Om Mahalakshmyai Namah',
    japaCount: 108,
    methodEn: [
      'Pink/red lotus, white-pink flowers, kheer, kamal-gatta',
      'Shri Yantra or Lakshmi-Kubera yantra on silver',
      'Light ghee diya in North-East corner of house',
      'Recite Shri Suktam (Rigveda) and Kanakdhara Stotra daily',
      'Donate to needy on Friday for amplified results',
    ],
    methodHi: [
      'गुलाबी/लाल कमल, श्वेत-गुलाबी पुष्प, खीर, कमल-गट्टा',
      'रजत पर श्री यंत्र या लक्ष्मी-कुबेर यंत्र',
      'घर के ईशान कोण में घी का दीप',
      'प्रतिदिन श्री सूक्त (ऋग्वेद) व कनकधारा स्तोत्र पाठ',
      'शुक्रवार को दान करें—फल कई गुना बढ़ता है',
    ],
    precautionsEn: [
      'Cleanliness of altar and home is paramount—Lakshmi resides where there is cleanliness',
      'Do not be greedy; Lakshmi flees from miserliness',
      'Speak truth and avoid harsh words',
    ],
    precautionsHi: [
      'मन्दिर व घर की पूर्ण स्वच्छता—जहाँ स्वच्छता वहाँ लक्ष्मी',
      'लोभ न करें; कृपणता से लक्ष्मी रुष्ट होती हैं',
      'सत्य भाषण व कटु वचनों का त्याग',
    ],
    sources: [
      { textEn: 'Shri Suktam — Rigveda Khila', textHi: 'श्री सूक्त — ऋग्वेद खिल' },
      { textEn: 'Kanakdhara Stotra by Adi Shankaracharya', textHi: 'कनकधारा स्तोत्र (आदि शंकराचार्य)' },
      { textEn: 'Mantra Maharnava', textHi: 'मंत्र महार्णव' },
      { textEn: 'Mantra Mahodadhi', textHi: 'मंत्र महोदधि', reference: 'Taranga 13' },
    ],
  },
  {
    id: 'gayatri',
    category: 'vedic',
    nameEn: 'Gayatri Mahasadhana',
    nameHi: 'गायत्री महासाधना',
    deityEn: 'Maa Gayatri (Savitri)',
    deityHi: 'माँ गायत्री (सावित्री)',
    purposeEn: 'Purification of intellect, awakening of divine wisdom, all-round upliftment',
    purposeHi: 'बुद्धि शुद्धि, दिव्य ज्ञान का जागरण, सर्वांगीण उत्थान',
    bestTithiEn: 'Shravan Purnima (Upakarma), Gayatri Jayanti (Jyeshtha Shukla Ekadashi)',
    bestTithiHi: 'श्रावण पूर्णिमा (उपाकर्म), गायत्री जयन्ती (ज्येष्ठ शुक्ल एकादशी)',
    bestVaarEn: 'Daily—mandatory for the Dvija (twice-born)',
    bestVaarHi: 'प्रतिदिन—द्विज वर्ण के लिए अनिवार्य',
    bestTimeEn: 'Three Sandhya: Pratah (sunrise), Madhyahna (noon), Sayam (sunset)',
    bestTimeHi: 'तीन संध्या: प्रातः (सूर्योदय), मध्याह्न (दोपहर), सायं (सूर्यास्त)',
    bestNakshatraEn: 'Hasta, Pushya, Shravana',
    bestNakshatraHi: 'हस्त, पुष्य, श्रवण',
    durationEn: 'Lifetime; Purascharan = 2,400,000 japa',
    durationHi: 'जीवन-पर्यन्त; पुरश्चरण = 24 लाख जप',
    mantra: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्',
    mantraTransliteration: 'Om Bhur Bhuvah Svah, Tat Savitur Varenyam, Bhargo Devasya Dhimahi, Dhiyo Yo Nah Prachodayat',
    japaCount: 108,
    methodEn: [
      'Begin only after Upanayan (sacred thread) or with guru permission',
      'Three Sandhyas: face East at sunrise, face up at noon, face West at sunset',
      'Use tulsi or rudraksha mala',
      'Pranayama before japa (anuloma-viloma)',
      'On completion, do hawan with samidha of palash + ghee',
    ],
    methodHi: [
      'उपनयन (यज्ञोपवीत) के बाद ही अथवा गुरु आज्ञा से प्रारम्भ करें',
      'तीनों संध्या: प्रातः पूर्व मुख, मध्याह्न ऊर्ध्व, सायं पश्चिम मुख',
      'तुलसी या रुद्राक्ष माला',
      'जप से पूर्व प्राणायाम (अनुलोम-विलोम)',
      'समाप्ति पर पलाश समिधा + घी से हवन',
    ],
    precautionsEn: [
      'Pronunciation (uchharan) of mantra must be precise—learn from a knowledgeable person',
      'Maintain satya, ahimsa, brahmacharya during sadhana periods',
      'Never recite during impurity (sutaka, ashaucha)',
    ],
    precautionsHi: [
      'मंत्र का उच्चारण शुद्ध हो—ज्ञानी व्यक्ति से सीखें',
      'साधना काल में सत्य, अहिंसा, ब्रह्मचर्य का पालन',
      'सूतक/अशौच काल में पाठ वर्जित',
    ],
    sources: [
      { textEn: 'Rigveda 3.62.10 (Rishi Vishvamitra)', textHi: 'ऋग्वेद 3.62.10 (विश्वामित्र)' },
      { textEn: 'Yajurveda, Samaveda, Atharvaveda — all four Vedas', textHi: 'चारों वेद — यजुर्वेद, सामवेद, अथर्ववेद' },
      { textEn: 'Gayatri Tantra', textHi: 'गायत्री तंत्र' },
    ],
  },
  {
    id: 'tara',
    category: 'tantric',
    nameEn: 'Maa Tara Sadhana',
    nameHi: 'माँ तारा साधना',
    deityEn: 'Maa Ugra-Tara (Nila-Saraswati)',
    deityHi: 'माँ उग्र-तारा (नील-सरस्वती)',
    purposeEn: 'Liberation, eloquence, swift removal of obstacles, crossing the ocean of samsara',
    purposeHi: 'मोक्ष, वाक्-सिद्धि, शीघ्र विघ्न नाश, संसार सागर से पार',
    bestTithiEn: 'Chaitra Shukla Navami (Tara Jayanti), Krishna Chaturdashi',
    bestTithiHi: 'चैत्र शुक्ल नवमी (तारा जयन्ती), कृष्ण चतुर्दशी',
    bestVaarEn: 'Tuesday',
    bestVaarHi: 'मंगलवार',
    bestTimeEn: 'Nishita Kaal',
    bestTimeHi: 'निशीथ काल',
    bestNakshatraEn: 'Pushya, Magha',
    bestNakshatraHi: 'पुष्य, मघा',
    durationEn: 'Purna anushthan = 100,000 japa',
    durationHi: 'पूर्ण अनुष्ठान = 1 लाख जप',
    mantra: 'ॐ ह्रीं स्त्रीं हुं फट्',
    mantraTransliteration: 'Om Hrim Strim Hum Phat',
    japaCount: 108,
    methodEn: [
      'Famous siddha-peetha: Tarapith (West Bengal)',
      'Blue cloth, blue lotus, ksheer offering',
      'Rudraksha mala; recite Tara Stotra of Vasishtha',
      '⚠️ Requires guru-diksha—an Ugra Mahavidya',
    ],
    methodHi: [
      'सिद्ध पीठ: तारापीठ (पश्चिम बंगाल)',
      'नील वस्त्र, नील कमल, खीर अर्पण',
      'रुद्राक्ष माला; वसिष्ठ रचित तारा स्तोत्र पाठ',
      '⚠️ गुरु-दीक्षा अनिवार्य—उग्र महाविद्या',
    ],
    precautionsEn: [
      'Not for beginners; never attempt without sampradaya guru',
      'Avoid this sadhana during pregnancy or mental illness',
    ],
    precautionsHi: [
      'प्रारम्भिक साधकों के लिए नहीं; सम्प्रदाय गुरु के बिना कभी न करें',
      'गर्भावस्था या मानसिक रोग की स्थिति में वर्जित',
    ],
    sources: [
      { textEn: 'Brahma Yamala', textHi: 'ब्रह्म यामल' },
      { textEn: 'Tara Tantra', textHi: 'तारा तंत्र' },
      { textEn: 'Rudrayamala Tantra', textHi: 'रुद्रयामल तंत्र' },
      { textEn: 'Mantra Mahodadhi', textHi: 'मंत्र महोदधि', reference: 'Taranga 5' },
    ],
  },
];
